### PR TITLE
Add RSS feed

### PR DESCRIPTION
**Pull request by wezm**
I'm interested to follow the progress of this project. This PR adds an RSS feed that allows people to subscribe in their feed reader of choice.

### CODE REVIEW

**Review by ddevault — APPROVED** [review]

**Comment by ddevault** [comment]
Thanks!

**Comment by wezm** [comment]
Still getting 404 for /feed.xml has the site been redeployed?

**Comment by ddevault** [comment]
Should be good to go now.

**Comment by wezm** [comment]
Yep working now, thanks.

**Comment by CameronNemo** [comment]
>BTW the blog RSS feed does not work for me, i tried on both livemarks and thunderbird (other RSS feeds work fine).

>edit: on livemarks when i click on the RSS button in firefox i see the list of posts, but when i subscribe i don't get the posts published, which is surprising.

https://old.reddit.com/r/linux/comments/depj03/wayfire_03_released/f304top/

**Pull request merged**
